image: registry.michelada.io/michelada/micheteca:latest

services:
  - postgres

stages:
  - build
  - lint
  - test
  - deploy

cache:
  paths:
    - vendor
    - node_modules
    - public/packs

before_script:
  - ruby -v
  - node -v
  - gem install bundler
  - bundle install -j $(nproc) --path vendor --full-index --clean
  - cp config/database.ci.yml config/database.yml

build:
  stage: build
  script:
    - bundle exec rake yarn:install
    - bundle exec rake webpacker:compile

rubocop:
  stage: lint
  script:
    - bundle exec rubocop

test:
  stage: test
  script:
    - bundle exec rake db:create RAILS_ENV=test
    - bundle exec rake db:test:prepare RAILS_ENV=test
    - bundle exec rake yarn:install
    - bundle exec rake webpacker:compile
    - bundle exec rake test

test_system:
  stage: test
  script:
    - bundle exec rake db:create RAILS_ENV=test
    - bundle exec rake db:test:prepare RAILS_ENV=test
    - bundle exec rake test:system

heroku:
  stage: deploy
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
    - heroku run rake db:migrate --app=$HEROKU_APP_NAME
  only:
    - master




